[workspace]
resolver = "3"
members = ["crates/*", "tests", "fuzz"]

[workspace.dependencies]
sierradb = { path = "crates/sierradb" }
sierradb-cluster = { path = "crates/sierradb-cluster" }
sierradb-protocol = { path = "crates/sierradb-protocol" }
sierradb-topology = { path = "crates/sierradb-topology" }

arrayvec = "0.7"
bincode = "2.0"
boomphf = "0.6"
bytes = "1.10"
config = { version = "0.15", default-features = false, features = [
  "convert-case",
  "ini",
  "json",
  "json5",
  "ron",
  "toml",
  "yaml",
] }
clap = "4.5"
crc32fast = "1.4"
directories = "6.0"
failsafe = "1.3.0"
futures = "0.3"
kameo = { git = "https://github.com/tqwewe/kameo", branch = "main" }
libp2p = "0.56"
rand = "0.9"
serde = "1.0"
smallvec = "1.15"
strum = { version = "0.27", features = ["derive"] }
tempfile = "3.16"
tokio = "1.44"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = "1.16"
valuable = "0.1.1"
